export const FETCH_USER_INFO_START = 'user/FETCH_USER_INFO_START';
export const FETCH_USER_INFO_SUCCESS = 'user/FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'user/FETCH_USER_INFO_FAILURE';
