version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11.6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: 'npm install'
      - run:
          name: Install firebase tools
          command: 'sudo npm install -g firebase-tools'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build ReactJS
          command: 'npm run build'
      - deploy:
          name: Deploy to Firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                firebase deploy --token=$FIREBASE_TOKEN --non-interactive
            fi